name: Publish apps
run-name: Version ${{ github.ref_name }}

on:
  workflow_dispatch: 
  push:
    tags:
      - '*'

jobs:
  check-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: '[]'
    steps:
      - name: Skip check
        run: echo "Skipping app check"

  publish-applications:
    needs: check-apps
    runs-on: ubuntu-latest
    steps:
      - name: Skip publish
        run: echo "Skipping publish"
